variables:
  FEISHU_BOT: ""

merge-request:
  image: argocd:latest
  stage: merge-request

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - |-
      message=$(helm template scripts/notification --set-string newMergeRequest.enabled=true \
        --set-string newMergeRequest.projectURL="$CI_MERGE_REQUEST_PROJECT_URL" \
        --set-string newMergeRequest.author="$CI_COMMIT_AUTHOR" \
        --set-string newMergeRequest.id="$CI_MERGE_REQUEST_IID" \
        --set-string newMergeRequest.title="$CI_MERGE_REQUEST_TITLE" \
        --set-string newMergeRequest.notes="$CI_COMMIT_MESSAGE" \
        --set-string newMergeRequest.assignee="louzhenghao@itiger.com" | yq -ojson)

      echo $message

      curl -H "Content-Type:application/json" -X POST -k $FEISHU_BOT -d "$message"

notification:
  image: argocd:latest
  stage: notification
  only:
    - master
  script:
    - |-
      bash scripts/notification.sh https://open.feishu.cn/open-apis/bot/v2/hook/97550911-bb49-448f-8ff0-69ebad408643 "$CI_COMMIT_MESSAGE" $CI_COMMIT_SHORT_SHA $CI_PROJECT_URL
